<?php

namespace Database\Seeders;

use Carbon\Carbon;
use App\Models\Food;
use App\Models\Menu;
use App\Models\User;
use App\Models\Admin;
use App\Models\Order;
use App\Models\Payment;
use App\Models\Philfct;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Student;
use App\Models\Guardian;
use App\Models\Purchase;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // SuperAdmin
        DB::table('users')->delete();
        $superAdminUser = [
            [
                'id' => 1,
                'email' => 'super@admin.com',
                'recoveryEmail' => 'super@recover.com',
                'password' => bcrypt('qwe'),
                'role' => 2,
                'created_at' => '2022-05-01'
            ],
        ];
        DB::table('admins')->delete();
        $superAdmin = [
            [
                'id' => 1,
                'firstName' => 'NSDAPS',
                'lastName' => 'Admin',
                'birthDate' => '2022-05-01',
                'sex' => 'A',
                'status' => 1,
                'created_at' => '2022-05-01',
                'user_id' => 1,
                'created_by' => 1,
            ]
        ];
        User::insert($superAdminUser);
        Admin::insert($superAdmin);

        // Admin
        $adminUser = [
            [
                'id' => 2,
                'email' => 'test@admin.com',
                'recoveryEmail' => 'admin@recover.com',
                'password' => bcrypt('123'),
                'role' => 1,
                'created_at' => '2022-05-01'
            ],
            [
                'id' => 4,
                'email' => 'delcjoshua10@gmail.com',
                'recoveryEmail' => 'admin@recover.com',
                'password' => bcrypt('123'),
                'role' => 1,
                'created_at' => '2022-05-01',
            ],
            [
                'id' => 5,
                'email' => 'jportugaliza@gmail.com',
                'recoveryEmail' => 'admin@recover.com',
                'password' => bcrypt('123'),
                'role' => 1,
                'created_at' => '2022-05-01'
            ],
        ];
        $admin = [
            [
                'id' => 2,
                'firstName' => 'Glen',
                'lastName' => 'Reyes',
                'birthDate' => '2022-05-01',
                'status' => 1,
                'sex' => 'M',
                'created_at' => '2022-05-01',
                'created_by' => 1,
                'user_id' => 2,
                'image' => 'admin/admins/1.png'
            ],
            [
                'id' => 3,
                'firstName' => 'Joshua',
                'lastName' => 'Dela Cruz',
                'birthDate' => '2022-05-01',
                'status' => 1,
                'sex' => 'F',
                'created_at' => '2022-05-01',
                'created_by' => 2,
                'user_id' => 4,
                'image' => 'admin/admins/2.png'
            ],
            [
                'id' => 4,
                'firstName' => 'Lydia',
                'lastName' => 'Portugaliza',
                'birthDate' => '2022-05-01',
                'status' => 1,
                'sex' => 'M',
                'created_at' => '2022-05-01',
                'created_by' => 2,
                'user_id' => 5,
                'image' => 'admin/admins/3.png'
            ]
        ];
        User::insert($adminUser);
        Admin::insert($admin);

        // Parents
        DB::table('parents')->delete();
        $parentUser = [
            [
                'id' => 3,
                'email' => 'test@parent.com',
                'recoveryEmail' => 'parent@recover.com',
                'password' => bcrypt('zxc'),
                'role' => 0,
                'created_at' => '2022-06-01'
            ],
            [
                'id' => 6,
                'email' => 'byronjames@gmail.com',
                'recoveryEmail' => 'titoko@gmail.com',
                'password' => bcrypt('zxc'),
                'role' => 0,
                'created_at' => '2022-06-01'
            ],
            [
                'id' => 7,
                'email' => 'salao_emman@gmail.com',
                'recoveryEmail' => 'delcjoshua1987@gmail.com',
                'password' => bcrypt('zxc'),
                'role' => 0,
                'created_at' => '2022-06-01'
            ],
        ];
        $parents = [
            [
                'firstName' => 'Karen',
                'lastName' => 'Reyes',
                'middleName' => 'Dela Cruz',
                'sex' => 'F',
                'address' => 'Pacita Complex, San Pedro, Laguna',
                'birthDate' => '1993-07-23',
                'status' => 1,
                'created_at' => '2022-06-01',
                'user_id' => 3,
                'created_by' => 2,
                'image' => 'admin/parents/1.png'
            ],
            [
                'firstName' => 'Byron James',
                'lastName' => 'Ramos',
                'middleName' => 'Regalado',
                'sex' => 'M',
                'address' => 'Villa Milagros, Rodriguez, Rizal',
                'birthDate' => '1993-07-23',
                'status' => 1,
                'created_at' => '2022-06-01',
                'user_id' => 6,
                'created_by' => 2,
                'image' => 'admin/parents/2.png'
            ],
            [
                'firstName' => 'Emmanuel',
                'lastName' => 'Salao',
                'middleName' => 'Noveno Cruz',
                'sex' => 'M',
                'address' => 'San Mateo, Rizal',
                'birthDate' => '1993-07-23',
                'status' => 1,
                'created_at' => '2022-06-01',
                'user_id' => 7,
                'created_by' => 2,
                'image' => 'admin/parents/3.png'
            ]
        ];
        User::insert($parentUser);
        Guardian::insert($parents);

        // Students
        DB::table('students')->delete();
        $students = [
            [
                'grade' => 4,
                'section' => 'Sampaguita',
                'adviser' => 'Abigayle Ramos',
                'firstName' => 'Karina',
                'lastName' => 'Reyes',
                'middleName' => 'Dela Cruz',
                'sex' => 'F',
                'birthDate' => '2012-09-17',
                'status' => 1,
                'created_at' => '2022-06-01',
                'parent_id' => 1,
                'created_by' => 2,
                'QR' => 'admin/qrs/1.png',
                'image' => 'admin/students/1.png'
            ],
            [
                'grade' => 4,
                'section' => 'Sampaguita',
                'adviser' => 'Abigayle Ramos',
                'firstName' => 'Queenierich',
                'lastName' => 'Reyes',
                'middleName' => 'Dela Cruz',
                'sex' => 'F',
                'birthDate' => '2012-09-17',
                'status' => 1,
                'created_at' => '2022-06-01',
                'parent_id' => 1,
                'created_by' => 2,
                'QR' => 'admin/qrs/2.png',
                'image' => 'admin/students/2.png'
            ],
            [
                'grade' => 4,
                'section' => 'Sampaguita',
                'adviser' => 'Abigayle Ramos',
                'firstName' => 'Aaron James',
                'lastName' => 'Ramos',
                'middleName' => 'Fernandez',
                'sex' => 'F',
                'birthDate' => '2012-09-17',
                'status' => 1,
                'created_at' => '2022-06-01',
                'parent_id' => 2,
                'created_by' => 2,
                'QR' => 'admin/qrs/3.png',
                'image' => 'admin/students/3.png'
            ],
            [
                'grade' => 4,
                'section' => 'Sampaguita',
                'adviser' => 'Abigayle Ramos',
                'firstName' => 'Jessica Marie Joy',
                'lastName' => 'Salao',
                'middleName' => 'Sy',
                'sex' => 'F',
                'birthDate' => '2012-09-17',
                'status' => 1,
                'created_at' => '2022-06-01',
                'parent_id' => 3,
                'created_by' => 2,
                'QR' => 'admin/qrs/4.png',
                'image' => 'admin/students/4.png'
            ],
            [
                'grade' => 4,
                'section' => 'Sampaguita',
                'adviser' => 'Abigayle Ramos',
                'firstName' => 'Rachelle Marianne',
                'lastName' => 'Dimaranan',
                'middleName' => 'Sarinas',
                'sex' => 'F',
                'birthDate' => '2012-09-17',
                'status' => 1,
                'created_at' => '2022-06-01',
                'parent_id' => 3,
                'created_by' => 2,
                'QR' => 'admin/qrs/5.png',
                'image' => 'admin/students/5.png'
            ]
        ];
        Student::insert($students);

        // Philfct
        DB::table('philfcts')->delete();
        // $philfcts = [
        //     [
        //         'id' => 1, // R014
        //         'philfct_id' => 'R014',
        //         'name' => 'Spaghetti',
        //         'kcal' => 83,
        //         'totFat' => 1,
        //         'satFat' => 0.35,
        //         'sugar' => 2.9,
        //         'sodium' => 277
        //     ],
        //     [
        //         'id' => 2, // 'R013',
        //         'philfct_id' => 'R013',
        //         'name' => 'Goto',
        //         'kcal' => 53,
        //         'totFat' => 1.3,
        //         'satFat' => 0.84,
        //         'sugar' => 0.2,
        //         'sodium' => 179
        //     ],
        //     [
        //         'id' => 3, // 'E102',
        //         'philfct_id' => 'E102',
        //         'name' => 'Turon',
        //         'kcal' => 259,
        //         'totFat' => 6.4,
        //         'satFat' => 5.41,
        //         'sugar' => 28.8,
        //         'sodium' => 89
        //     ],
        //     [
        //         'id' => 4, // Rice
        //         'philfct_id' => null,
        //         'name' => 'Rice',
        //         'kcal' => 129,
        //         'totFat' => 0.2,
        //         'satFat' => 0.05,
        //         'sugar' => 0.1,
        //         'sodium' => 3
        //     ],
        //     [
        //         'id' => 5, // 'Hotdog',
        //         'philfct_id' => null,
        //         'name' => 'Hotdog',
        //         'kcal' => 226,
        //         'totFat' => 17,
        //         'satFat' => 6.21,
        //         'sugar' => 2.9,
        //         'sodium' => 698
        //     ]
        // ];
        $philfcts = [
            [
                'id' => 1, // R014
                'philfct_id' => 'R014',
                'name' => 'Spaghetti',
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 2, // Rice
                'philfct_id' => null,
                'name' => 'Rice',
                'kcal' => 129,
                'totFat' => 0.2,
                'satFat' => 0.05,
                'sugar' => 0.1,
                'sodium' => 3
            ],
            [
                'id' => 3, 
                'philfct_id' => null,
                'name' => 'Fried Chicken',
                'kcal' => 226,
                'totFat' => 17,
                'satFat' => 6.21,
                'sugar' => 2.9,
                'sodium' => 698
            ],
            [
                'id' => 4, 
                'philfct_id' => null,
                'name' => 'Pork Siomai',
                'kcal' => 298,
                'totFat' => 16.7,
                'satFat' => 4.9,
                'sugar' => 1.2,
                'sodium' => 291
            ],
            [
                'id' => 5, 
                'philfct_id' => null,
                'name' => 'Pork Siopao',
                'kcal' => 294,
                'totFat' => 11.2,
                'satFat' => 4.75,
                'sugar' => 0,
                'sodium' => 0
            ],
            [
                'id' => 6, 
                'philfct_id' => null,
                'name' => 'Tocino',
                'kcal' => 206,
                'totFat' => 6.4,
                'satFat' => 2.2,
                'sugar' => 20.2,
                'sodium' => 1037
            ],
            [
                'id' => 7, 
                'philfct_id' => null,
                'name' => 'Sweet Ham',
                'kcal' => 117,
                'totFat' => 4.4,
                'satFat' => 1.34,
                'sugar' => 2.9,
                'sodium' => 1208
            ],
            [
                'id' => 8, 
                'philfct_id' => null,
                'name' => 'Boiled Chicken Egg',
                'kcal' => 166,
                'totFat' => 12,
                'satFat' => 3.58,
                'sugar' => 0.4,
                'sodium' => 136
            ],
            [
                'id' => 9, 
                'philfct_id' => null,
                'name' => 'Turon',
                'kcal' => 259,
                'totFat' => 6.4,
                'satFat' => 5.41,
                'sugar' => 28.8,
                'sodium' => 89
            ],
            [
                'id' => 10, 
                'philfct_id' => null,
                'name' => 'Zesto Grape Flavor',
                'kcal' => 90,
                'totFat' => 0.2,
                'satFat' => 0,
                'sugar' => 21.6,
                'sodium' => 14
            ],
            [
                'id' => 11, 
                'philfct_id' => null,
                'name' => 'Zesto Guava Flavor',
                'kcal' => 92,
                'totFat' => 0.6,
                'satFat' => 0.3,
                'sugar' => 17.6,
                'sodium' => 14
            ],
            [
                'id' => 12, 
                'philfct_id' => null,
                'name' => 'Zesto Strawberry Flavor',
                'kcal' => 100,
                'totFat' => 0.4,
                'satFat' => 0,
                'sugar' => 23.2,
                'sodium' => 10
            ],
            [
                'id' => 13, 
                'philfct_id' => null,
                'name' => 'Buko Juice',
                'kcal' => 78,
                'totFat' => 0.4,
                'satFat' => 0.34,
                'sugar' => 10.2,
                'sodium' => 14
            ],
            [
                'id' => 14, 
                'philfct_id' => null,
                'name' => 'Coco honet biscuit',
                'kcal' => 63.42,
                'totFat' => 1.554,
                'satFat' => 2.856,
                'sugar' => 4.2,
                'sodium' => 1.12
            ],
            [
                'id' => 15, 
                'philfct_id' => null,
                'name' => 'Curly tops',
                'kcal' => 25.9,
                'totFat' => 0.8235,
                'satFat' => 2.58,
                'sugar' => 0.5,
                'sodium' => 0.5
            ],
            [
                'id' => 16, 
                'philfct_id' => null,
                'name' => 'Peanut Brittle',
                'kcal' => 118.32,
                'totFat' => 5.808,
                'satFat' => 1.2672,
                'sugar' => 11.76,
                'sodium' => 101.76
            ],
            [
                'id' => 17, 
                'philfct_id' => null,
                'name' => 'Chopsuey',
                'kcal' => 70,
                'totFat' => 2.8,
                'satFat' => 1.3,
                'sugar' => 4,
                'sodium' => 354
            ],
        ];
        Philfct::insert($philfcts);

        // Foods
        DB::table('foods')->delete();
        // $foods = [
        //     [
        //         'id' => '1',
        //         'name' => 'Spaghetti',
        //         'description' => 'Filipino Style Classic Spaghetti',
        //         'price' => 50.00,
        //         'stock' => 20,
        //         'servingSize' => 100.00,
        //         'calcKcal' => 83,
        //         'calcTotFat' => 1,
        //         'calcSatFat' => 0.35,
        //         'calcSugar' => 2.9,
        //         'calcSodium' => 277,
        //         'created_at' => '2022-05-15',
        //         'philfct_id' => 1, // 'R014',
        //         // created_by
        //         'created_by' => 2
        //     ],
        //     [
        //         'id' => '2',
        //         'name' => 'Goto',
        //         'description' => 'Classic Goto with Beef Tripe',
        //         'price' => 50.00,
        //         'stock' => 20,
        //         'servingSize' => 100.00,
        //         'calcKcal' => 53,
        //         'calcTotFat' => 1.3,
        //         'calcSatFat' => 0.84,
        //         'calcSugar' => 0.2,
        //         'calcSodium' => 179,
        //         'created_at' => '2022-05-15',
        //         'philfct_id' => 2, // 'R013',
        //         'created_by' => 2
        //     ],
        //     [
        //         'id' => '3',
        //         'name' => 'Turon',
        //         'description' => 'Sweet Banana Lumpia',
        //         'price' => 50.00,
        //         'stock' => 20,
        //         'servingSize' => 100.00,
        //         'calcKcal' => 259,
        //         'calcTotFat' => 6.4,
        //         'calcSatFat' => 5.41,
        //         'calcSugar' => 28.8,
        //         'calcSodium' => 89,
        //         'created_at' => '2022-05-15',
        //         'philfct_id' => 3, // 'E012',
        //         'created_by' => 2
        //     ]
        // ];
        $foods = [
            [
                'id' => 1,
                'name' => 'Spaghetti',
                'calcKcal' => 83,
                'calcTotFat' => 1,
                'calcSatFat' => 0.35,
                'calcSugar' => 2.9,
                'calcSodium' => 277,
                'description' => 'Filipino sweet style spaghetti',
                'type' => 3,
                'price' => 50,
                'servingSize' => 100,
                'philfct_id' => 2,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 4,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/spaghetti.jpg'
            ],
            [
                'id' => 2,
                'name' => 'Rice',
                'calcKcal' => 129,
                'calcTotFat' => 0.2,
                'calcSatFat' => 0.05,
                'calcSugar' => 0.1,
                'calcSodium' => 3,
                'description' => 'One cup rice/kanin',
                'type' => 0,
                'price' => 15,
                'servingSize' => 100,
                'philfct_id' => 2,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 4,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/rice.jpg'
            ],
            [
                'id' => 3,
                'name' => 'Hotdog',
                'calcKcal' => 226,
                'calcTotFat' => 17,
                'calcSatFat' => 6.21,
                'calcSugar' => 2.9,
                'calcSodium' => 698,
                'description' => '1 pc hotdog',
                'type' => 3,
                'price' => 25,
                'servingSize' => 100,
                'philfct_id' => null,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 9,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/hotdog.jpg'
            ],
            [
                'id' => 4,
                'name' => 'Corned Beef',
                'calcKcal' => 168,
                'calcTotFat' => 10.7,
                'calcSatFat' => 4.51,
                'calcSugar' => 0,
                'calcSodium' => 567,
                'description' => 'Cooked Corned Beef',
                'type' => 3,
                'price' => 25,
                'servingSize' => 100,
                'philfct_id' => null,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 7,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/corned-beef.jpg'
            ],
            [
                'id' => 5,
                'name' => 'Luncheon Meat',
                'calcKcal' => 307,
                'calcTotFat' => 26.4,
                'calcSatFat' => 8.9,
                'calcSugar' => 3,
                'calcSodium' => 956,
                'description' => 'Maling with 1 cup rice',
                'type' => 3,
                'price' => 25,
                'servingSize' => 100,
                'philfct_id' => null,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 10,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/luncheon meat.jpg'
            ],
            [
                'id' => 6,
                'name' => 'Maling',
                'calcKcal' => 296,
                'calcTotFat' => 25,
                'calcSatFat' => 8.9,
                'calcSugar' => 2.8,
                'calcSodium' => 902,
                'description' => 'Maling with 1 cup rice',
                'type' => 3,
                'price' => 25,
                'servingSize' => 100,
                'philfct_id' => null,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 10,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/maling.jpeg'
            ],
            [
                'id' => 7,
                'name' => 'Fried Chicken',
                'calcKcal' => null,
                'calcTotFat' => null,
                'calcSatFat' => null,
                'calcSugar' => null,
                'calcSodium' => null,
                'description' => '1 pc fried chicken with 1 cup rice',
                'type' => 3,
                'price' => 40,
                'servingSize' => 100,
                'philfct_id' => 3,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => null,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/fried-chicken.jpg'
            ],
            [
                'id' => 8,
                'name' => 'Longganisa',
                'calcKcal' => 315,
                'calcTotFat' => 22.7,
                'calcSatFat' => 6.93,
                'calcSugar' => 0,
                'calcSodium' => 714,
                'description' => 'Longganisa',
                'type' => 3,
                'price' => 25,
                'servingSize' => 100,
                'philfct_id' => null,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 10,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/longganisa.jpg'
            ],
            [
                'id' => 9,
                'name' => 'Goto',
                'calcKcal' => 71,
                'calcTotFat' => 1.1,
                'calcSatFat' => 0.9,
                'calcSugar' => 0.1,
                'calcSodium' => 1,
                'description' => 'with laman',
                'type' => 3,
                'price' => 25,
                'servingSize' => 100,
                'philfct_id' => null,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 4,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/goto.jpg'
            ],
            [
                'id' => 10,
                'name' => 'Pork Siomai',
                'calcKcal' => 298,
                'calcTotFat' => 16.7,
                'calcSatFat' => 4.9,
                'calcSugar' => 1.2,
                'calcSodium' => 291,
                'description' => 'Pork Siomai with Toyo and Calamansi',
                'type' => 3,
                'price' => 25,
                'servingSize' => 100,
                'philfct_id' => 4,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 7,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/pork-siomai.jpg'
            ],
            [
                'id' => 11,
                'name' => 'Pork Siopao',
                'calcKcal' => 294,
                'calcTotFat' => 11.2,
                'calcSatFat' => 4.75,
                'calcSugar' => 0,
                'calcSodium' => 0,
                'description' => 'Pork Siopao Bola Bola',
                'type' => 2,
                'price' => 15,
                'servingSize' => 100,
                'philfct_id' => 5,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 6,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/pork-siopao.jpeg'
            ],
            [
                'id' => 12,
                'name' => 'Tocino',
                'calcKcal' => 206,
                'calcTotFat' => 6.4,
                'calcSatFat' => 2.2,
                'calcSugar' => 20.2,
                'calcSodium' => 1037,
                'description' => 'Pork Tocino with Rice',
                'type' => 3,
                'price' => 40,
                'servingSize' => 100,
                'philfct_id' => 6,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 9,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/tocino.jpg'
            ],
            [
                'id' => 13,
                'name' => 'Sweet Ham',
                'calcKcal' => 117,
                'calcTotFat' => 4.4,
                'calcSatFat' => 1.34,
                'calcSugar' => 2.9,
                'calcSodium' => 1208,
                'description' => 'serving of sweet pork ham with rice',
                'type' => 3,
                'price' => 15,
                'servingSize' => 100,
                'philfct_id' => 7,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 7,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/ham.jpg'
            ],
            [
                'id' => 14,
                'name' => 'Boiled Chicken Egg',
                'calcKcal' => 166,
                'calcTotFat' => 12,
                'calcSatFat' => 3.58,
                'calcSugar' => 0.4,
                'calcSodium' => 136,
                'description' => '1 pc boiled chicken egg',
                'type' => 0,
                'price' => 15,
                'servingSize' => 100,
                'philfct_id' => 8,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 7,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/boiled-egg.jpg'
            ],
            [
                'id' => 15,
                'name' => 'Cheesedog',
                'calcKcal' => 245,
                'calcTotFat' => 18.1,
                'calcSatFat' => 6.19,
                'calcSugar' => 5,
                'calcSodium' => 1088,
                'description' => '1 pc cheesedog',
                'type' => 3,
                'price' => 25,
                'servingSize' => 100,
                'philfct_id' => null,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 10,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/hotdog.jpg'
            ],
            [
                'id' => 16,
                'name' => 'Turon',
                'calcKcal' => 259,
                'calcTotFat' => 6.4,
                'calcSatFat' => 5.41,
                'calcSugar' => 28.8,
                'calcSodium' => 89,
                'description' => '1 pc banana turon',
                'type' => 2,
                'price' => 15,
                'servingSize' => 100,
                'philfct_id' => 9,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 9,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/turon.jpg'
            ],
            [
                'id' => 17,
                'name' => 'Zesto Grape Flavor',
                'calcKcal' => 90,
                'calcTotFat' => 0.2,
                'calcSatFat' => 0,
                'calcSugar' => 21.6,
                'calcSodium' => 14,
                'description' => 'Zesto Fruit juice drink, grape flavor',
                'type' => 1,
                'price' => 10,
                'servingSize' => 200,
                'philfct_id' => 10,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/zesto-grape.jpg'
            ],
            [
                'id' => 18,
                'name' => 'Zesto Guava Flavor',
                'calcKcal' => 92,
                'calcTotFat' => 0.6,
                'calcSatFat' => 0.3,
                'calcSugar' => 17.6,
                'calcSodium' => 14,
                'description' => 'Zesto Fruit juice drink, guava flavor',
                'type' => 1,
                'price' => 10,
                'servingSize' => 200,
                'philfct_id' => 11,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/zesto-guava.png'
            ],
            [
                'id' => 19,
                'name' => 'Zesto Strawberry Flavor',
                'calcKcal' => 100,
                'calcTotFat' => 0.4,
                'calcSatFat' => 0,
                'calcSugar' => 23.2,
                'calcSodium' => 10,
                'description' => 'Zesto Fruit juice drink, strawberry flavor',
                'type' => 1,
                'price' => 10,
                'servingSize' => 200,
                'philfct_id' => 12,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 6,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/zesto-strawberry.jpg'
            ],
            [
                'id' => 20,
                'name' => 'Buko Juice',
                'calcKcal' => 78,
                'calcTotFat' => 0.4,
                'calcSatFat' => 0.34,
                'calcSugar' => 10.2,
                'calcSodium' => 14,
                'description' => 'Buko juice palamig',
                'type' => 1,
                'price' => 10,
                'servingSize' => 200,
                'philfct_id' => 13,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/buko-juice.jpg'
            ],
            [
                'id' => 21,
                'name' => 'Coco honey biscuit',
                'calcKcal' => 63.42,
                'calcTotFat' => 1.554,
                'calcSatFat' => 2.856,
                'calcSugar' => 4.2,
                'calcSodium' => 1.12,
                'description' => 'cocohoney biscuit',
                'type' => 2,
                'price' => 10,
                'servingSize' => 14,
                'philfct_id' => 14,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 8,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/coco-honey.png'
            ],
            [
                'id' => 22,
                'name' => 'Curly tops',
                'calcKcal' => 25.9,
                'calcTotFat' => 0.8235,
                'calcSatFat' => 2.58,
                'calcSugar' => 0.5,
                'calcSodium' => 0.5,
                'description' => 'curly tops milk chocolate candy',
                'type' => 0,
                'price' => 3,
                'servingSize' => 5,
                'philfct_id' => 15,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 9,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/curly-tops.jpg'
            ],
            [
                'id' => 23,
                'name' => 'Peanut Brittle',
                'calcKcal' => 118.32,
                'calcTotFat' => 5.808,
                'calcSatFat' => 1.2672,
                'calcSugar' => 11.76,
                'calcSodium' => 101.76,
                'description' => 'peanut brittle candy snack',
                'type' => 0,
                'price' => 20,
                'servingSize' => 20,
                'philfct_id' => 16,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 11,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/peanut-brittle.jpg'
            ],
            [
                'id' => 24,
                'name' => 'Chopsuey',
                'calcKcal' => 70,
                'calcTotFat' => 2.8,
                'calcSatFat' => 1.3,
                'calcSugar' => 4,
                'calcSodium' => 354,
                'description' => 'serving of chopsuey vegetable stew',
                'type' => 3,
                'price' => 25,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/chopsuey.jpg'
            ],
            [
                'id' => 25, 
                'name' => 'Pork BBQ',
                'calcKcal' => 408,
                'calcTotFat' => 29,
                'calcSatFat' => 10.25,
                'calcSugar' => 0,
                'calcSodium' => 340,
                'description' => 'pork barbecque/inihaw w/ rice',
                'type' => 3,
                'price' => 40,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 9,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/pork-bbq.jpg'
            ],
            [
                'id' => 26, 
                'name' => 'Kikyam',
                'calcKcal' => 129,
                'calcTotFat' => 2.1,
                'calcSatFat' => 0,
                'calcSugar' => 0,
                'calcSodium' => 0,
                'description' => 'Kikyam/Tusok-tusok',
                'type' => 2,
                'price' => 5,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 4,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/kikyam.jpg'
            ],
            [
                'id' => 27, 
                'name' => 'Pritong Bangus',
                'calcKcal' => 188,
                'calcTotFat' => 10.4,
                'calcSatFat' => 0,
                'calcSugar' => 0,
                'calcSodium' => 106,
                'description' => 'Fried Bangus w/ rice',
                'type' => 3,
                'price' => 50,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/daing-na-bangus.jpg'
            ],
            [
                'id' => 28, 
                'name' => 'Inihaw na bangus',
                'calcKcal' => 137,
                'calcTotFat' => 4.8,
                'calcSatFat' => 0,
                'calcSugar' => 0,
                'calcSodium' => 82,
                'description' => 'Bangus/Broiled',
                'type' => 3,
                'price' => 60,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/inihaw-bangus.jpg'
            ],
            [
                'id' => 29, 
                'name' => 'Lechong Manok',
                'calcKcal' => 226,
                'calcTotFat' => 12,
                'calcSatFat' => 4.07,
                'calcSugar' => 1.5,
                'calcSodium' => 716,
                'description' => 'Roasted Chicken w/ rice',
                'type' => 3,
                'price' => 50,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 8,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/lechon-manok.jpg'
            ],
            [
                'id' => 30, 
                'name' => 'Embutido',
                'calcKcal' => 164,
                'calcTotFat' => 8.5,
                'calcSatFat' => 3.4,
                'calcSugar' => 5.1,
                'calcSodium' => 939,
                'description' => 'Embotido w/ rice',
                'type' => 3,
                'price' => 45,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 9,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/embutido.jpg'
            ],
            [
                'id' => 31, 
                'name' => 'Chicken Nuggets',
                'calcKcal' => 220,
                'calcTotFat' => 11.2,
                'calcSatFat' => 2.22,
                'calcSugar' => 0.7,
                'calcSodium' => 520,
                'description' => 'Chicken Nuggets',
                'type' => 3,
                'price' => 35,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 7,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/chicken-nuggets.jpg'
            ],
            [
                'id' => 32, 
                'name' => 'Corned Beef',
                'calcKcal' => 168,
                'calcTotFat' => 10.7,
                'calcSatFat' => 4.51,
                'calcSugar' => 0,
                'calcSodium' => 567,
                'description' => 'Canned Corned Beef',
                'type' => 3,
                'price' => 35,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 7,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/corned-beef.jpg'
            ],
            [
                'id' => 33, 
                'name' => 'Chicharon',
                'calcKcal' => 591,
                'calcTotFat' => 36.5,
                'calcSatFat' => 7.25,
                'calcSugar' => 0,
                'calcSodium' => 472,
                'description' => 'Canned Corned Beef',
                'type' => 2,
                'price' => 30,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 9,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/chicharon.jpg'
            ],
            [
                'id' => 34, 
                'name' => 'Lechon Kawali',
                'calcKcal' => 245,
                'calcTotFat' => 21.8,
                'calcSatFat' => 7.95,
                'calcSugar' => 0,
                'calcSodium' => 61,
                'description' => 'Pork Belly Fried w/ rice',
                'type' => 3,
                'price' => 60,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 8,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/lechon-kawali.jpg'
            ],
            [
                'id' => 35, 
                'name' => 'Polvoron',
                'calcKcal' => 469,
                'calcTotFat' => 16.4,
                'calcSatFat' => 10.17,
                'calcSugar' => 46.2,
                'calcSodium' => 194,
                'description' => 'Polvoron',
                'type' => 2,
                'price' => 8,
                'servingSize' => 27,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 10,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/polvoron.jpg'
            ],
            [
                'id' => 36, 
                'name' => 'Pork Siopao',
                'calcKcal' => 294,
                'calcTotFat' => 11.2,
                'calcSatFat' => 4.75,
                'calcSugar' => 0,
                'calcSodium' => 0,
                'description' => 'Pork Siopao Asado',
                'type' => 2,
                'price' => 35,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 6,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/pork-siopao.jpeg'
            ],
            [
                'id' => 37, 
                'name' => 'Champorado',
                'calcKcal' => 97,
                'calcTotFat' => 0.2,
                'calcSatFat' => 0.11,
                'calcSugar' => 4.8,
                'calcSodium' => 13,
                'description' => 'Champorado w/ milk',
                'type' => 3,
                'price' => 20,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 4,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/champorado.jpg'
            ],
            [
                'id' => 38, 
                'name' => 'Yakult',
                'calcKcal' => 71,
                'calcTotFat' => 0.2,
                'calcSatFat' => 0.13,
                'calcSugar' => 6,
                'calcSodium' => 61,
                'description' => 'Cultured milk drink',
                'type' => 1,
                'price' => 12,
                'servingSize' => 80,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/yakult.jpg'
            ],
            [
                'id' => 39, 
                'name' => 'Pritong Baka',
                'calcKcal' => 152,
                'calcTotFat' => 6.4,
                'calcSatFat' => 2.49,
                'calcSugar' => 0,
                'calcSodium' => 44,
                'description' => 'Pritong Baka w/ rice',
                'type' => 3,
                'price' => 40,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 6,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/pritong-baka.jpg'
            ],
            [
                'id' => 40, 
                'name' => 'Pritong Liempo',
                'calcKcal' => 245,
                'calcTotFat' => 21.8,
                'calcSatFat' => 7.95,
                'calcSugar' => 0,
                'calcSodium' => 61,
                'description' => 'Pritong Liempo w/ rice',
                'type' => 3,
                'price' => 40,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 8,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/pritong-liempo.jpg'
            ],
            [
                'id' => 41, 
                'name' => 'Banana Cue',
                'calcKcal' => 183,
                'calcTotFat' => 2.6,
                'calcSatFat' => 2.21,
                'calcSugar' => 36.2,
                'calcSodium' => 6,
                'description' => 'Fried banana coated with caramelized sugar',
                'type' => 2,
                'price' => 15,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 7,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/banana-cue.jpg'
            ],
            [
                'id' => 42, 
                'name' => 'Maruya',
                'calcKcal' => 240,
                'calcTotFat' => 3.9,
                'calcSatFat' => 3.3,
                'calcSugar' => 25,
                'calcSodium' => 190,
                'description' => 'Banana Fritter',
                'type' => 2,
                'price' => 15,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 9,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/maruya.jpg'
            ],
            [
                'id' => 43, 
                'name' => 'Banana Latundan',
                'calcKcal' => 105,
                'calcTotFat' => 0.3,
                'calcSatFat' => 0.1,
                'calcSugar' => 13,
                'calcSodium' => 3,
                'description' => 'Banana Latundan',
                'type' => 2,
                'price' => 5,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/banana-latundan.jpg'
            ],
            [
                'id' => 44, 
                'name' => 'Banana Lakatan',
                'calcKcal' => 126,
                'calcTotFat' => 0.2,
                'calcSatFat' => 0.07,
                'calcSugar' => 15.6,
                'calcSodium' => 2,
                'description' => 'Banana Lakatan',
                'type' => 2,
                'price' => 5,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/banana-lakatan.png'
            ],
            [
                'id' => 45, 
                'name' => 'Red Apple',
                'calcKcal' => 67,
                'calcTotFat' => 0.1,
                'calcSatFat' => 0.02,
                'calcSugar' => 12,
                'calcSodium' => 2,
                'description' => 'Red Apple',
                'type' => 2,
                'price' => 25,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/red-apple.jpg'
            ],
            [
                'id' => 46, 
                'name' => 'Chips cheese flavor',
                'calcKcal' => 489,
                'calcTotFat' => 24.1,
                'calcSatFat' => 12.66,
                'calcSugar' => 2.5,
                'calcSodium' => 672,
                'description' => 'Tortillos',
                'type' => 2,
                'price' => 15,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 10,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/chips-cheese.jpg'
            ],
            [
                'id' => 47, 
                'name' => 'Corn chips BBQ Flavor',
                'calcKcal' => 535,
                'calcTotFat' => 30.7,
                'calcSatFat' => 16.13,
                'calcSugar' => 0.3,
                'calcSodium' => 758,
                'description' => 'Nachos, Leslies, Doritos',
                'type' => 2,
                'price' => 15,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 10,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/cornchips-bbq.png'
            ],
            [
                'id' => 48, 
                'name' => 'Corn chips Nachos Flavor',
                'calcKcal' => 528,
                'calcTotFat' => 30,
                'calcSatFat' => 15.76,
                'calcSugar' => 0.3,
                'calcSodium' => 682,
                'description' => 'Tostillas',
                'type' => 2,
                'price' => 15,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 10,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/cornchips-nachos.jpg'
            ],
            [
                'id' => 49, 
                'name' => 'Corn chips Natural Flavor',
                'calcKcal' => 527,
                'calcTotFat' => 29.1,
                'calcSatFat' => 15.29,
                'calcSugar' => 0.3,
                'calcSodium' => 514,
                'description' => 'Nachos, Lesliesm Doritos',
                'type' => 2,
                'price' => 15,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 9,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/cornchips-natural.jpg'
            ],
            [
                'id' => 50, 
                'name' => 'Potato Chips cheese flavor',
                'calcKcal' => 540,
                'calcTotFat' => 33.4,
                'calcSatFat' => 17.54,
                'calcSugar' => 0.3,
                'calcSodium' => 453,
                'description' => 'Oishi Potato Cheese Flavor',
                'type' => 2,
                'price' => 15,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 9,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/potato-chips-cheese.png'
            ],
            [
                'id' => 51, 
                'name' => 'Fishda Kroepeck',
                'calcKcal' => 502,
                'calcTotFat' => 27,
                'calcSatFat' => 20.26,
                'calcSugar' => 0.2,
                'calcSodium' => 729,
                'description' => 'Fishda',
                'type' => 2,
                'price' => 15,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 10,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/fishda.png'
            ],
            [
                'id' => 52, 
                'name' => 'Oishi prawn crackers',
                'calcKcal' => 502,
                'calcTotFat' => 27,
                'calcSatFat' => 20.26,
                'calcSugar' => 0.2,
                'calcSodium' => 729,
                'description' => 'Oishiiii',
                'type' => 2,
                'price' => 15,
                'servingSize' => 100,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 10,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/prawn-crackers.png'
            ],
            [
                'id' => 53, 
                'name' => 'Del monte apple flavor',
                'calcKcal' => 100,
                'calcTotFat' => 0.4,
                'calcSatFat' => 0.06,
                'calcSugar' => 20.2,
                'calcSodium' => 8,
                'description' => 'Apple Drink',
                'type' => 1,
                'price' => 20,
                'servingSize' => 200,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/delmonte-apple.jpg'
            ],
            [
                'id' => 54, 
                'name' => 'Zesto Mango Flavor',
                'calcKcal' => 114,
                'calcTotFat' => 0.4,
                'calcSatFat' => 0.1,
                'calcSugar' => 26.4,
                'calcSodium' => 20,
                'description' => 'Mango Drink',
                'type' => 1,
                'price' => 12,
                'servingSize' => 200,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 6,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/zesto-mango.jpg'
            ],
            [
                'id' => 55, 
                'name' => 'Del Monte Orange and Pineapple Flavor',
                'calcKcal' => 94,
                'calcTotFat' => 0.4,
                'calcSatFat' => 0.06,
                'calcSugar' => 20.4,
                'calcSodium' => 6,
                'description' => 'Orange and Pineapple Drink',
                'type' => 1,
                'price' => 20,
                'servingSize' => 200,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/delmonte-orange.jpg'
            ],
            [
                'id' => 56, 
                'name' => 'Zesto Orange Flavor',
                'calcKcal' => 86,
                'calcTotFat' => 0.4,
                'calcSatFat' => 0.04,
                'calcSugar' => 14.4,
                'calcSodium' => 4,
                'description' => 'Orange Drink',
                'type' => 1,
                'price' => 12,
                'servingSize' => 200,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/zesto-orange.png'
            ],
            [
                'id' => 57, 
                'name' => 'Cola Softdrinks',
                'calcKcal' => 82,
                'calcTotFat' => 0.2,
                'calcSatFat' => 0,
                'calcSugar' => 18.8,
                'calcSodium' => 8,
                'description' => 'Cola Softdrinks',
                'type' => 1,
                'price' => 20,
                'servingSize' => 200,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/cola-softdrinks.png'
            ],
            [
                'id' => 58, 
                'name' => 'Royal Orange Softdrinks',
                'calcKcal' => 92,
                'calcTotFat' => 0,
                'calcSatFat' => 0,
                'calcSugar' => 19.4,
                'calcSodium' => 24,
                'description' => 'Royal Orange Softdrinks',
                'type' => 1,
                'price' => 20,
                'servingSize' => 200,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/orange-softdrinks.png'
            ],
            [
                'id' => 59, 
                'name' => 'Soyabean Chocolate Drink',
                'calcKcal' => 152,
                'calcTotFat' => 0.6,
                'calcSatFat' => 0.1,
                'calcSugar' => 20.8,
                'calcSodium' => 140,
                'description' => 'Vitamilk, Vitasoy',
                'type' => 1,
                'price' => 25,
                'servingSize' => 200,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/chocolate-drink.jpg'
            ],
            [
                'id' => 60, 
                'name' => 'Soyabean Drink',
                'calcKcal' => 102,
                'calcTotFat' => 0.16,
                'calcSatFat' => 0.18,
                'calcSugar' => 8,
                'calcSodium' => 4,
                'description' => 'Vitamilk, Vitasoy',
                'type' => 1,
                'price' => 25,
                'servingSize' => 200,
                'philfct_id' => 17,
                'created_by' => 2,
                'updated_by' => 3,
                'stock' => 40,
                'grade' => 5,
                'created_at' => Carbon::today()->format('Y-m-d'),
                'image' => 'admin/foods/soybean-drink.jpeg'
            ]


        ];
        Food::insert($foods);

        // Menu
        DB::table('menus')->delete();
        $menus = [
            // Permanents beverages
            [
                'food_id' => 17,
                'status' => 0,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => null,
                'removed_at' => null,
                'created_by' => 2
            ],
            [
                'food_id' => 18,
                'status' => 0,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => null,
                'removed_at' => null,
                'created_by' => 2
            ],
            [
                'food_id' => 19,
                'status' => 0,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => null,
                'removed_at' => null,
                'created_by' => 2
            ],
            [
                'food_id' => 20,
                'status' => 0,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => null,
                'removed_at' => null,
                'created_by' => 2
            ],
            // Permanent Snacks
            [
                'food_id' => 11,
                'status' => 0,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => null,
                'removed_at' => null,
                'created_by' => 2
            ],
            [
                'food_id' => 16,
                'status' => 0,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => null,
                'removed_at' => null,
                'created_by' => 2
            ],
            [
                'food_id' => 21,
                'status' => 0,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => null,
                'removed_at' => null,
                'created_by' => 2
            ],
            // Permanent Cooked Meals
            [
                'food_id' => 1,
                'status' => 0,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => null,
                'removed_at' => null,
                'created_by' => 2
            ],
            [
                'food_id' => 3,
                'status' => 0,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => null,
                'removed_at' => null,
                'created_by' => 2
            ],
            [
                'food_id' => 4,
                'status' => 0,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => null,
                'removed_at' => null,
                'created_by' => 2
            ],
            [
                'food_id' => 5,
                'status' => 0,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => null,
                'removed_at' => null,
                'created_by' => 2
            ],
            [
                'food_id' => 6,
                'status' => 0,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => null,
                'removed_at' => null,
                'created_by' => 2
            ],
            // Temporary COoked Meals
            [
                'food_id' => 7,
                'status' => 1,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => Carbon::today()->format('Y-m-d'),
                'removed_at' => '2022-11-18',
                'created_by' => 2
            ],
            [
                'food_id' => 8,
                'status' => 1,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => Carbon::today()->format('Y-m-d'),
                'removed_at' => '2022-11-18',
                'created_by' => 2
            ],
            [
                'food_id' => 9,
                'status' => 1,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => Carbon::today()->format('Y-m-d'),
                'removed_at' => '2022-11-18',
                'created_by' => 2
            ],
            [
                'food_id' => 10,
                'status' => 1,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => Carbon::today()->format('Y-m-d'),
                'removed_at' => '2022-11-18',
                'created_by' => 2
            ],
            [
                'food_id' => 12,
                'status' => 1,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'displayed_at' => Carbon::today()->format('Y-m-d'),
                'removed_at' => '2022-11-18',
                'created_by' => 2
            ]
        ];
        Menu::insert($menus);

        // Payments
        DB::table('payments')->delete();
        $payments = [
            [
                'id' => 1,
                'parent_id' => 1,
                'student_id' => 1,
                'method' => 'GCash',
                'referenceNo' => 123456789
            ]
        ];
        Payment::insert($payments);

        // Purchases
        DB::table('purchases')->delete();
        $purchases = [
            [
                'id' => 1,
                'parent_id' => 1,
                'student_id' => 1,
                'totalAmount' => 50.00,
                'totalKcal' => 83,
                'totalTotFat' => 1,
                'totalSatFat' => 0.35,
                'totalSugar' => 2.9,
                'totalSodium' => 277,
                'payment_id' => 1,
                'claimStatus' => 0,
                'type' => 0,
                'created_at' => Carbon::yesterday()->format('Y-m-d'),
                'served_by' => 2
            ],
            [
                'id' => 2,
                'parent_id' => 1,
                'student_id' => 2,
                'totalAmount' => 60.00,
                'totalKcal' => 515,
                'totalTotFat' => 20.2,
                'totalSatFat' => 15.31,
                'totalSugar' => 27.5,
                'totalSodium' => 1630,
                'payment_id' => 1,
                'claimStatus' => 0,
                'type' => 0,
                'served_by' => 2,
                'created_at' => Carbon::yesterday()->format('Y-m-d')
            ],
            [
                'id' => 3,
                'parent_id' => 1,
                'student_id' => 2,
                'totalAmount' => 60.00,
                'totalKcal' => 515,
                'totalTotFat' => 20.2,
                'totalSatFat' => 15.31,
                'totalSugar' => 27.5,
                'totalSodium' => 1630,
                'payment_id' => 1,
                'claimStatus' => 0,
                'type' => 0,
                'served_by' => 2,
                'created_at' => Carbon::yesterday()->format('Y-m-d')
            ],
            [
                'id' => 4,
                'parent_id' => 1,
                'student_id' => 1,
                'totalAmount' => 60.00,
                'totalKcal' => 515,
                'totalTotFat' => 20.2,
                'totalSatFat' => 15.31,
                'totalSugar' => 27.5,
                'totalSodium' => 1630,
                'payment_id' => 1,
                'claimStatus' => 0,
                'type' => 0,
                'served_by' => 2,
                'created_at' => '2022-11-15'
            ],
            [
                'id' => 5,
                'parent_id' => 1,
                'student_id' => 2,
                'totalAmount' => 60.00,
                'totalKcal' => 515,
                'totalTotFat' => 20.2,
                'totalSatFat' => 15.31,
                'totalSugar' => 27.5,
                'totalSodium' => 1630,
                'payment_id' => 1,
                'claimStatus' => 0,
                'type' => 0,
                'served_by' => 2,
                'created_at' => '2022-11-15'
            ],
            [
                'id' => 6,
                'parent_id' => 1,
                'student_id' => 1,
                'totalAmount' => 60.00,
                'totalKcal' => 515,
                'totalTotFat' => 20.2,
                'totalSatFat' => 15.31,
                'totalSugar' => 27.5,
                'totalSodium' => 1630,
                'payment_id' => 1,
                'claimStatus' => 0,
                'type' => 0,
                'served_by' => 2,
                'created_at' => '2022-11-15'
            ],
            [
                'id' => 7,
                'parent_id' => 1,
                'student_id' => 2,
                'totalAmount' => 60.00,
                'totalKcal' => 515,
                'totalTotFat' => 20.2,
                'totalSatFat' => 15.31,
                'totalSugar' => 27.5,
                'totalSodium' => 1630,
                'payment_id' => 1,
                'claimStatus' => 0,
                'type' => 0,
                'served_by' => 2,
                'created_at' => '2022-11-15'
            ],
            [
                'id' => 8,
                'parent_id' => 1,
                'student_id' => 1,
                'totalAmount' => 60.00,
                'totalKcal' => 515,
                'totalTotFat' => 20.2,
                'totalSatFat' => 15.31,
                'totalSugar' => 27.5,
                'totalSodium' => 1630,
                'payment_id' => 1,
                'claimStatus' => 0,
                'type' => 0,
                'served_by' => 2,
                'created_at' => '2022-11-15'
            ]
        ];
        Purchase::insert($purchases);

        // Orders
        DB::table('orders')->delete();
        $orders = [
            [
                'id' => 1,
                'purchase_id' => 1,
                'food_id' => 1,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 2,
                'purchase_id' => 2,
                'food_id' => 3,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 3,
                'purchase_id' => 2,
                'food_id' => 24,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 4,
                'purchase_id' => 2,
                'food_id' => 17,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 5,
                'purchase_id' => 3,
                'food_id' => 9,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 6,
                'purchase_id' => 3,
                'food_id' => 16,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 7,
                'purchase_id' => 1,
                'food_id' => 3,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 8,
                'purchase_id' => 4,
                'food_id' => 3,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 9,
                'purchase_id' => 5,
                'food_id' => 1,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 10,
                'purchase_id' => 5,
                'food_id' => 17,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 11,
                'purchase_id' => 6,
                'food_id' => 3,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 12,
                'purchase_id' => 6,
                'food_id' => 21,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 13,
                'purchase_id' => 6,
                'food_id' => 10,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 14,
                'purchase_id' => 7,
                'food_id' => 24,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 15,
                'purchase_id' => 8,
                'food_id' => 3,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 16,
                'purchase_id' => 8,
                'food_id' => 21,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ],
            [
                'id' => 17,
                'purchase_id' => 8,
                'food_id' => 23,
                'quantity' => 1,
                'amount' => 50.00,
                'kcal' => 83,
                'totFat' => 1,
                'satFat' => 0.35,
                'sugar' => 2.9,
                'sodium' => 277
            ]
        ];
        Order::insert($orders);
    }
}
